name: "HTMLProofer"
author: "austinchambers"
description: "Test your rendered HTML files to make sure they're accurate."

inputs:
  directory:
    description: "The directory to scan"
    required: true
  arguments:
      description: "HTMLProofer options"
      required: false

runs:
  using: "docker"
  image: "docker://austinchambers/htmlproofer"
  entrypoint: "/entrypoint.sh"

branding:
  icon: "check"
  color: "green"
