name: Docker Image CI

on:
  push:
    branches: 
      - master

jobs:

  build:
    runs-on: ubuntu-latest
 
    steps:
      - uses: actions/checkout@v1

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag austinchambers/htmlproofer
        
      - name: Login to Docker Hub
        run: docker login --username=${{ secrets.DOCKER_USER }} --password=${{ secrets.DOCKER_TOKEN }}
      
      - name: Publish to Docker Registry
        run: docker push austinchambers/htmlproofer
